version: '3.5'

services:
    php:
        container_name: tree-app
        build:
            context: docker/php
        tty: true
        user: ${C_USER}
        volumes:
            - .:/var/www/app
            - ./docker/php/php-ini-extra.ini:/usr/local/etc/php/conf.d/docker-php-ext-php-ini-extra.ini

